# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Pyshnov | iOS Developer
email: pyshnovdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A driven iOS developer. Love making beautiful apps and designing clear APIs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pyshnovt.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
