# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Тимоха
email: lightwight99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Говорят, это описание использует гугл в поисковых запросах. Ну ладно, пусть использует и дальше.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pyshnovt.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
